#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
const outPath = join(root, 'src', 'version.ts');
const nextContents = `// Generated by scripts/gen-version.mjs. Do not edit by hand.
export const VERSION = ${JSON.stringify(pkg.version)};
`;

const existing = existsSync(outPath) ? readFileSync(outPath, 'utf-8') : '';
if (existing === nextContents) {
  console.log(`src/version.ts ok (${pkg.version}) - no write`);
} else {
  writeFileSync(outPath, nextContents);
  console.log(`src/version.ts <- ${pkg.version}`);
}
